ARG cdns_ver=1.10.0
ARG cdns_filter_ver=0.2.2

FROM ghcr.io/wranders/lab-builder AS builder
ARG cdns_ver cdns_filter_ver
RUN git clone --branch "v${cdns_ver}" --single-branch --depth 1 \
    --config advice.detachedHead=False \
    https://github.com/coredns/coredns.git /srv/
RUN go get -u "github.com/wranders/coredns-filter@v${cdns_filter_ver}"
RUN sed -i '/^cache:cache/i filter:github.com/wranders/coredns-filter' /srv/plugin.cfg
RUN make
RUN useradd coredns --no-log-init -U -M -s /sbin/nologin
RUN chown coredns:coredns /srv/coredns
RUN setcap 'cap_net_bind_service=+ep' /srv/coredns
RUN mkdir /srv/user && \
    echo $(grep coredns /etc/group) > /srv/user/group && \
    echo $(grep coredns /etc/passwd) > /srv/user/passwd && \
    chown root:root /srv/user/{group,passwd} && \
    chmod 0644 /srv/user/{group,passwd}

FROM scratch
LABEL org.opencontainers.image.source="https://github.com/wranders/lab" \
    org.opencontainers.image.authors="W Anders <w@doubleu.codes>" \
    org.opencontainers.image.title="dns" \
    org.opencontainers.image.description="CoreDNS customized"
COPY --from=builder \
    /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem \
    /etc/pki/ca-trust/extracted/pem/
COPY --from=builder /sbin/nologin /sbin/
COPY --from=builder /srv/user/group /srv/user/passwd /etc/
COPY --from=builder /srv/coredns /coredns
EXPOSE 53 53/udp
USER coredns
ENTRYPOINT ["/coredns"]
