ARG yq_version=4.26.1
ARG step_version=0.21.0
ARG helm_version=3.9.2
ARG cosign_version=1.10.0

FROM registry.fedoraproject.org/fedora:36

LABEL org.opencontainers.image.source="https://github.com/wranders/lab" \
    org.opencontainers.image.authors="W Anders <w@doubleu.codes>" \
    org.opencontainers.image.title="workbox" \
    org.opencontainers.image.description="Tools to configure and deploy Lab"

ARG yq_version step_version helm_version cosign_version TARGETARCH

RUN dnf install -y --setopt=install_weak_deps=False --nodocs \
    bash-completion \
    ncurses \
    jq \
    util-linux \
    && dnf clean all

WORKDIR /root

COPY ./install.sh /root/install.sh
RUN chmod +x /root/install.sh

RUN /root/install.sh install_yq $yq_version $TARGETARCH && \
    /root/install.sh install_cosign $cosign_version $TARGETARCH && \
    /root/install.sh install_stepcli $step_version $TARGETARCH && \
    /root/install.sh install_helm $helm_version $TARGETARCH

RUN useradd workbox --uid 1000 -G wheel && \
    echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-nopasswd &&\
    chmod 600 /etc/sudoers.d/wheel-nopasswd

RUN chown workbox: /srv
WORKDIR /srv
USER workbox

ENTRYPOINT [ "/usr/bin/bash" ]

