# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Build CoreOS Assembler
on:
  schedule:
  - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:36
      options: --privileged
    steps:
    - run: dnf install -y git moby-engine
    - uses: actions/checkout@v3
      with:
        repository: coreos/coreos-assembler
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v2
      id: buildx
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        labels: |
          org.opencontainers.image.source="https://github.com/wranders/lab"
        tags: |
          ghcr.io/wranders/coreos-assembler:latest
          quay.io/wranders/coreos-assembler:latest