# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
---
name: Build Workbox
on:
  push:
    paths:
    - 'containers/workbox/*'
    - '!containers/README.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64
    - uses: docker/setup-buildx-action@v2
      id: buildx
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        file: containers/workbox/Containerfile
        platforms: linux/amd64,linux/arm64
        push: |
          ghcr.io/wranders/lab-workbox:latest
          quay.io/wranders/lab-workbox:latest